import { useCallback, useState, useEffect, useRef } from 'react';
import {
    ReactFlow,
    MiniMap,
    Controls,
    Background,
    useNodesState,
    useEdgesState,
    addEdge,
    useReactFlow,
    ReactFlowProvider
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import * as d3 from 'd3-force';
import API from '../services/api';

// Main Component Wrapper to provide ReactFlow context
export default function KnowledgeGraph() {
    return (
        <ReactFlowProvider>
            <KnowledgeGraphInner />
        </ReactFlowProvider>
    );
}

function KnowledgeGraphInner() {
    const { fitView } = useReactFlow();
    const [nodes, setNodes, onNodesChange] = useNodesState([]);
    const [edges, setEdges, onEdgesChange] = useEdgesState([]);
    const [loadingGraph, setLoadingGraph] = useState(false);

    // Chatbox / Events states
    const [events, setEvents] = useState([]);
    const [selectedEventIds, setSelectedEventIds] = useState(new Set());
    const [chatHistory, setChatHistory] = useState([
        { role: 'ai', text: 'Select events from your intelligence feed below and click "Relate ✨" to discover hidden connections and generate a new knowledge graph.' }
    ]);
    const [isRelating, setIsRelating] = useState(false);
    const [pendingGraphData, setPendingGraphData] = useState(null); // Graph generated by AI, waiting to be visualized

    useEffect(() => {
        fetchEvents();
    }, []);

    const fetchEvents = async () => {
        try {
            const res = await API.get('/events');
            setEvents(res.data);
        } catch (err) {
            console.error(err);
        }
    };

    const toggleEventSelection = (id) => {
        const newSet = new Set(selectedEventIds);
        if (newSet.has(id)) {
            newSet.delete(id);
        } else {
            if (newSet.size >= 5) {
                alert("You can only select up to 5 events at a time for relating.");
                return;
            }
            newSet.add(id);
        }
        setSelectedEventIds(newSet);
    };

    const handleRelate = async () => {
        if (selectedEventIds.size === 0) return;

        const idsArray = Array.from(selectedEventIds);
        setIsRelating(true);
        setPendingGraphData(null);

        // Add user message
        setChatHistory(prev => [...prev, { role: 'user', text: `Please relate the ${idsArray.length} selected events.` }]);

        try {
            const res = await API.post('/relate', { event_ids: idsArray });
            const data = res.data;

            if (data.error) throw new Error(data.error);

            // Add AI explanation
            setChatHistory(prev => [...prev, { role: 'ai', text: data.reasoning }]);

            // Store graph data for visualization
            if (data.graph && data.graph.nodes && data.graph.nodes.length > 0) {
                setPendingGraphData(data.graph);
            }

        } catch (err) {
            console.error(err);
            setChatHistory(prev => [...prev, { role: 'ai', text: `Error generating insights: ${err.message}` }]);
        } finally {
            setIsRelating(false);
        }
    };

    const handleVisualize = () => {
        if (!pendingGraphData) return;

        setLoadingGraph(true);
        setTimeout(() => {
            applyForceLayout(pendingGraphData);
            setLoadingGraph(false);
            setPendingGraphData(null); // hide button once visualized
        }, 300); // UI delay for feel
    };

    // Physics Engine with d3-force
    const applyForceLayout = (graphData) => {
        // Prepare nodes
        const d3Nodes = graphData.nodes.map((n) => ({
            id: n.id,
            data: { label: n.id, type: n.type, domain: n.domain }
        }));

        // Prepare links
        const d3Links = graphData.edges.map((e) => ({
            source: e.source,
            target: e.target,
            label: e.relation
        }));

        // Filter out links where source or target doesn't exist in nodes
        const validNodeIds = new Set(d3Nodes.map(n => n.id));
        const validLinks = d3Links.filter(l => validNodeIds.has(l.source) && validNodeIds.has(l.target));

        // Create simulation
        const simulation = d3.forceSimulation(d3Nodes)
            .force("link", d3.forceLink(validLinks).id((d) => d.id).distance(150))
            .force("charge", d3.forceManyBody().strength(-800))
            .force("center", d3.forceCenter(400, 300))
            .force("collision", d3.forceCollide().radius(60))
            .stop();

        // Run simulation statically to get final positions immediately
        for (let i = 0; i < 300; ++i) simulation.tick();

        // Convert back to ReactFlow format
        const rfNodes = d3Nodes.map((node) => ({
            id: node.id,
            position: { x: node.x, y: node.y },
            data: node.data,
            style: {
                background: 'var(--bg-card)',
                color: 'var(--text-primary)',
                border: '1px solid var(--accent-primary)',
                borderRadius: '8px',
                padding: '10px 15px',
                boxShadow: '0 4px 12px rgba(99, 102, 241, 0.2)',
                minWidth: '120px',
                textAlign: 'center'
            }
        }));

        const rfEdges = validLinks.map((link, idx) => ({
            id: `e-${link.source.id}-${link.target.id}-${idx}`,
            source: link.source.id,
            target: link.target.id,
            label: link.label,
            animated: true,
            style: { stroke: 'var(--accent-cyan)', strokeWidth: 2 },
            labelStyle: { fill: 'var(--text-secondary)', fontWeight: 600, fontSize: 11, background: 'rgba(10,14,26,0.8)' },
            labelBgStyle: { fill: 'rgba(10,14,26,0.8)', color: '#fff', fillOpacity: 0.8 },
            labelBgPadding: [4, 4],
        }));

        setNodes(rfNodes);
        setEdges(rfEdges);

        setTimeout(() => {
            fitView({ padding: 0.2, duration: 800 });
        }, 50);
    };

    const onConnect = useCallback((params) => setEdges((eds) => addEdge(params, eds)), [setEdges]);

    return (
        <div className="page-container" style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>

            <div style={{ display: 'flex', gap: '20px', flex: 1, minHeight: 0 }}>
                {/* Main Graph Area */}
                <div className="card" style={{ flex: 1, position: 'relative', padding: 0, overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
                    <div style={{ position: 'absolute', top: 20, left: 20, zIndex: 10, background: 'rgba(10, 14, 26, 0.8)', padding: '12px 16px', borderRadius: '12px', backdropFilter: 'blur(10px)', border: '1px solid var(--border-primary)' }}>
                        <h1 style={{ fontSize: 20, margin: 0, display: 'flex', alignItems: 'center', gap: 8 }}>
                            <span style={{ color: 'var(--accent-primary)' }}>⚲</span> Ontology Graph
                        </h1>
                    </div>

                    {nodes.length === 0 && !loadingGraph ? (
                        <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', opacity: 0.3, pointerEvents: 'none' }}>
                            <div style={{ fontSize: 80, marginBottom: 20 }}>🕸️</div>
                            <h2>Awaiting Visuals</h2>
                            <p>Generate relationships in the chat panel to spawn the graph.</p>
                        </div>
                    ) : (
                        <ReactFlow
                            nodes={nodes}
                            edges={edges}
                            onNodesChange={onNodesChange}
                            onEdgesChange={onEdgesChange}
                            onConnect={onConnect}
                            fitView
                            style={{ background: 'transparent' }}
                        >
                            <Controls />
                            <MiniMap
                                nodeStrokeColor={(n) => 'var(--accent-primary)'}
                                nodeColor={(n) => 'var(--bg-tertiary)'}
                                maskColor="rgba(10, 14, 26, 0.8)"
                            />
                            <Background variant="dots" gap={12} size={1} color="var(--border-secondary)" />
                        </ReactFlow>
                    )}

                    {loadingGraph && (
                        <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(10, 14, 26, 0.7)', zIndex: 20, backdropFilter: 'blur(4px)' }}>
                            <div className="loading-spinner"></div>
                            <div style={{ color: 'var(--text-primary)', fontSize: 14, fontWeight: 600, marginLeft: 12 }}>Simulating Physics...</div>
                        </div>
                    )}
                </div>

                {/* Intelligence Chat Panel */}
                <div className="card" style={{ width: '400px', display: 'flex', flexDirection: 'column', padding: 0, overflow: 'hidden' }}>
                    <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--border-primary)', background: 'rgba(99,102,241,0.05)' }}>
                        <h3 style={{ fontSize: 16, margin: 0, display: 'flex', alignItems: 'center', gap: 8 }}>
                            <span style={{ fontSize: 20 }}>💬</span> Intelligence Synthesis
                        </h3>
                    </div>

                    {/* Chat History Area */}
                    <div style={{ flex: 1, overflowY: 'auto', padding: '20px', display: 'flex', flexDirection: 'column', gap: '16px', background: 'var(--bg-primary)' }}>
                        {chatHistory.map((msg, i) => (
                            <div key={i} className={`chat-message ${msg.role}`}>
                                <div className="msg-avatar">
                                    {msg.role === 'ai' ? '🤖' : '👤'}
                                </div>
                                <div className="msg-bubble">
                                    {msg.text}
                                </div>
                            </div>
                        ))}

                        {isRelating && (
                            <div className="chat-message ai">
                                <div className="msg-avatar">🤖</div>
                                <div className="msg-bubble" style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                                    <div className="loading-spinner" style={{ width: 14, height: 14, borderWidth: 2 }}></div>
                                    <span className="loading-dots" style={{ fontSize: 13, color: 'var(--text-secondary)' }}>Gemini is reasoning</span>
                                </div>
                            </div>
                        )}

                        {pendingGraphData && !isRelating && (
                            <div style={{ display: 'flex', justifyContent: 'center', marginTop: 10, animation: 'fadeInUp 0.3s ease' }}>
                                <button className="btn btn-primary" onClick={handleVisualize} style={{ padding: '12px 24px', fontSize: 14, borderRadius: 20, background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)', boxShadow: '0 4px 15px rgba(16,185,129,0.3)' }}>
                                    <span style={{ fontSize: 18 }}>📊</span> Visualize Relationships
                                </button>
                            </div>
                        )}
                    </div>

                    {/* Event Selection Area */}
                    <div style={{ height: '35%', display: 'flex', flexDirection: 'column', borderTop: '1px solid var(--border-primary)', background: 'var(--bg-card)' }}>
                        <div style={{ padding: '12px 16px', borderBottom: '1px solid var(--border-secondary)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                            <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', textTransform: 'uppercase' }}>Select Events ({selectedEventIds.size}/5)</span>
                            <button
                                className="btn btn-primary"
                                onClick={handleRelate}
                                disabled={selectedEventIds.size === 0 || isRelating}
                                style={{ padding: '6px 14px', fontSize: 12 }}
                            >
                                Relate ✨
                            </button>
                        </div>
                        <div style={{ flex: 1, overflowY: 'auto', padding: '10px' }}>
                            {events.length === 0 ? (
                                <div style={{ fontSize: 12, color: 'var(--text-muted)', textAlign: 'center', marginTop: 20 }}>No intelligence events found in feed.</div>
                            ) : (
                                <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                                    {events.map((e) => (
                                        <div
                                            key={e.id}
                                            onClick={() => toggleEventSelection(e.id)}
                                            style={{
                                                padding: '10px 12px',
                                                background: selectedEventIds.has(e.id) ? 'rgba(99,102,241,0.1)' : 'var(--bg-tertiary)',
                                                border: `1px solid ${selectedEventIds.has(e.id) ? 'var(--accent-primary)' : 'var(--border-secondary)'}`,
                                                borderRadius: '8px',
                                                cursor: 'pointer',
                                                transition: 'all 0.2s ease',
                                                display: 'flex',
                                                gap: '10px'
                                            }}
                                        >
                                            <div style={{
                                                width: 16, height: 16, borderRadius: 4,
                                                border: `1px solid ${selectedEventIds.has(e.id) ? 'var(--accent-primary)' : 'var(--text-muted)'}`,
                                                background: selectedEventIds.has(e.id) ? 'var(--accent-primary)' : 'transparent',
                                                flexShrink: 0, marginTop: 2, display: 'flex', alignItems: 'center', justifyContent: 'center'
                                            }}>
                                                {selectedEventIds.has(e.id) && <span style={{ color: 'white', fontSize: 10 }}>✓</span>}
                                            </div>
                                            <div>
                                                <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-primary)', marginBottom: 4, lineHeight: 1.3 }}>{e.event_title}</div>
                                                <div style={{ fontSize: 10, color: 'var(--accent-cyan)' }}>{e.domain.toUpperCase()}</div>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
